# build-winee.yml
name: Compilar Wine (Configuración Personalizada)

on:
  workflow_dispatch:
    inputs:
      wine_version:
        description: 'Versión de Wine a compilar (ej: 9.0)'
        required: true
        default: '9.0'
        type: string

permissions:
  contents: write  # Permite que GITHUB_TOKEN cree un Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Establecer variables de versión
      run: |
        echo "WINE_VERSION=${{ github.event.inputs.wine_version }}" >> $GITHUB_ENV
        echo "Compilando Wine versión: ${{ github.event.inputs.wine_version }}"

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt --fix-broken install -y
        sudo apt install -y \
          debootstrap \
          perl \
          git \
          wget \
          xz-utils \
          bubblewrap \
          autoconf \
          flex \
          bison \
          gcc-multilib \
          g++-multilib \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxfixes-dev \
          libxxf86vm-dev \
          libxrender-dev \
          libxinerama-dev \
          libgl-dev \
          libglu-dev \
          libosmesa6-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libpcap-dev \
          libdbus-1-dev \
          libssl-dev \
          libasound2-dev \
          libpulse-dev \
          libudev-dev \
          libcups2-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libxml2-dev \
          libvulkan-dev \
          vulkan-tools \
          libvulkan1 \
          mesa-vulkan-drivers \
          mingw-w64 \
          gettext \
          libgettextpo-dev \
          # Dependencias agregadas de build.sh
          libglvnd-dev \
          libgnutls28-dev

    - name: Comprobar directorio de trabajo
      run: |
        echo "Directorio de trabajo actual: $(pwd)"
        ls -la
        echo "Versión a compilar: ${{ env.WINE_VERSION }}"
          
    - name: Clonar código fuente de Wine
      run: |
        git clone https://github.com/KreitinnSoftware/wine.git
        cd wine
        # Usar la versión proporcionada en la entrada
        git checkout wine-${{ github.event.inputs.wine_version }}
        

    - name: Configurar y compilar Wine (64-bit, sin GStreamer)
      run: |
        cd wine
        mkdir -p /tmp/wine-install
        sudo chmod 777 -R /tmp/wine-install

        # Crear directorio de compilación
        mkdir -p build-win64
        cd build-win64
        export CROSSCC="x86_64-w64-mingw32-gcc"
        export CROSSCXX="x86_64-w64-mingw32-g++"
        export CFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CXXFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CROSSCFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CROSSCXXFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"

        # Configurar Wine 64-bit, basado en la configuración de build.sh
        # Se eliminaron las opciones de wow64, gstreamer e idioma
        ../configure \
          --enable-win64 \
          --prefix=/tmp/wine-install \
          --with-x \
          --with-vulkan \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --without-gettext \
          --disable-nls \
          --with-opengl \
          --with-gnutls \
          --with-xinput \
          --with-xinput2 \
          --without-gstreamer \
          --without-oss \
          --without-dbus \
          --without-sane \
          --without-pcap \
          --without-pcsclite \
          --disable-winemenubuilder \
          --disable-win16 \
          --disable-tests \
          --without-xinerama \
          --without-cups \
          --without-capi \
          --without-gphoto \
          --without-osmesa \
          --without-udev \
          --without-usb \
          --without-v4l2 \
          --without-wayland \
          --without-xshm \
          --without-xxf86vm \
          --without-sdl \
          --without-netapi \
          --without-opencl
          
        # Compilar Wine
        echo "Iniciando compilación de Wine 64-bit..."
        make -j$(nproc)

    - name: Instalar Wine y obtener información de la versión
      run: |
        cd wine/build-win64
        make install

        VERSION="${{ env.WINE_VERSION }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Versión de Wine: $VERSION - Compilación 64-bit personalizada"

    - name: Preparar empaquetado
      run: |
        mkdir -p wine-package/opt/wine
        cp -r /tmp/wine-install/* wine-package/opt/wine/

    - name: Crear archivo comprimido
      run: |
        tar -czf wine-${{ env.WINE_VERSION }}-win64-custom.tar.gz wine-package/
        echo "Empaquetado completado:"
        ls -lh wine-*.tar.gz

    - name: Subir artefacto de compilación
      uses: actions/upload-artifact@v4
      with:
        name: wine-${{ env.WINE_VERSION }}-win64-custom
        path: wine-${{ env.WINE_VERSION }}-win64-custom.tar.gz

    - name: Publicar en GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.WINE_VERSION }}-win64-custom
        name: Wine ${{ env.WINE_VERSION }} (64-bit, Configuración Personalizada)
        body: |
          # Wine ${{ env.WINE_VERSION }} - 64-bit, Configuración Personalizada
          
          ## Información de la Versión
          - **Versión de Wine**: ${{ env.WINE_VERSION }}
          - **Arquitectura**: Win64 (solo para aplicaciones de 64 bits)
          - **Plataforma**: Termux (Android)
          - **Configuración**: Basada en build.sh, sin GStreamer.
          
          ## Características
          ✓ Arquitectura Win64
          ✓ Soporte para la API gráfica Vulkan y OpenGL

          ## Información de Compilación
          - Fecha de compilación: ${{ github.event.head_commit.timestamp }}
          - Commit: ${{ github.sha }}
          - Workflow: ${{ github.workflow }}
        files: wine-${{ env.WINE_VERSION }}-win64-custom.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Mostrar información de la versión
      run: |
        echo "✅ Compilación de Wine 64-bit completada"
        echo "Número de versión: ${{ env.WINE_VERSION }}"
        echo "Arquitectura: x86_64 (Win64)"
        echo "Entorno: Termux"
        echo "Multimedia: Sin soporte para GStreamer"

